# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lsm5FcYAJVLXtsQKTMCuZ3b6G1r7XvGM/Vy9jAJOv05MZ2O/5Qmim1exwcQmadpC6PkH0RcAk7d8Lam68JxMzsmsm3PV4JY7hF//E9F4+6wW+Ed9oPCMQV7m/JiG1TFlvQOT8WMLcF+tu4kET2gWfLSpKFBydJFENgGW26qPV1N8eat0Mpse+t4Maextv2dqKnT14jW+NxZ81Cvd7DQVif6GetfZ/EWX3Uj6JWQXyEG/fMd+2aiHS+Q56rlxZ+ihUb+h5NG6lbzIPfTV4isoyMeXBRfGT6gtk7mlNdJqe/lcG/3CQEiwTCIQpJt3vlNOAagtYxMTfioGp+48mQmMgFl8UI9ly/VBOIjMSoqC7VtB+a9bu8B8W+z+GQazDA1YSGnFDVoikyI/EnJDhr54BNMLcV8SjWdIGuWP8oUgpPsS+7ItF1+tOEUIasD2bHjpnkiRXkr7BaduHdlc1Gmaaxeywvs7rgCXIcSh20iFJ4j2EDKwYKFLPMCJ1pEEl7UsBpQUee7c3SqT4C+8A1zYPQtGzghd/5gC8VYuaqwEZTpOA5kCaqwslAINHLcL5el2xSSbEl3iNzsv4MHmzUxUNEjoq903cahSTFui0Yozl/LVtivBEY2v3u8UNjKMNT+inTDoQHo1X0Olw2VmE0R29vgBVCtrgs3Yf7KMChnSuhM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
