travis:
  secure:
    BINSTAR_TOKEN: lsm5FcYAJVLXtsQKTMCuZ3b6G1r7XvGM/Vy9jAJOv05MZ2O/5Qmim1exwcQmadpC6PkH0RcAk7d8Lam68JxMzsmsm3PV4JY7hF//E9F4+6wW+Ed9oPCMQV7m/JiG1TFlvQOT8WMLcF+tu4kET2gWfLSpKFBydJFENgGW26qPV1N8eat0Mpse+t4Maextv2dqKnT14jW+NxZ81Cvd7DQVif6GetfZ/EWX3Uj6JWQXyEG/fMd+2aiHS+Q56rlxZ+ihUb+h5NG6lbzIPfTV4isoyMeXBRfGT6gtk7mlNdJqe/lcG/3CQEiwTCIQpJt3vlNOAagtYxMTfioGp+48mQmMgFl8UI9ly/VBOIjMSoqC7VtB+a9bu8B8W+z+GQazDA1YSGnFDVoikyI/EnJDhr54BNMLcV8SjWdIGuWP8oUgpPsS+7ItF1+tOEUIasD2bHjpnkiRXkr7BaduHdlc1Gmaaxeywvs7rgCXIcSh20iFJ4j2EDKwYKFLPMCJ1pEEl7UsBpQUee7c3SqT4C+8A1zYPQtGzghd/5gC8VYuaqwEZTpOA5kCaqwslAINHLcL5el2xSSbEl3iNzsv4MHmzUxUNEjoq903cahSTFui0Yozl/LVtivBEY2v3u8UNjKMNT+inTDoQHo1X0Olw2VmE0R29vgBVCtrgs3Yf7KMChnSuhM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
