travis:
  secure:
    BINSTAR_TOKEN: nhhEXl7O3+HYT64EGGDy1Dy4kjr4On0SLsyKPAklpIMesbFO+q9hwzBGEnSWr5jrFd9tZueUr6p1E/qNtZ2RL9GiD++cG30gohlm6/VaO5rKxGMAgilGFodqZ0AgMflnQpl6919UAW1B9xoSd2jtw6PhJjhFcgjuU6jqVETKeUpmbNEuirKukBsFXX7YkU6snLmcXQSDAGT1iHGAEr8QM6FY3s8qdqnhDR1UkYv3n7dhsqBnxRjdx3bRtk9PsuRlYmON+mPFjjXcy5ohr6H1SUYKAFiteq/BFVmI+LphwarSnpVLRHDZ1vGGVO7wW839E+rNCcXVHyfND/GojRZ0bmM8vuG4LZ8jFVHE9tL7u5XDL6hsyJ4Nf2o5a/TTblVJMrqr2n0/Bw/0+CKU3tNei2QICqjdGIcW3tkFJFVAELQyAfFa4JsTLhCC0OOiPiNAIXKvnDjQnOUGSFxZutkZ/j3vWmCwVKc/Hvpi8pDSlEuiF3+yai8vxaaKZl1dCCdLUbs5H3DdiYzKxAnKKVTADVp6DJuADVR2wjprILl9DsbilrZft/JyKH1VfpG4nx82UrYIh5OmOZHAGtfPK0JjSY0RqM53tUgYRSkuc6ARTwB++PxsyroASOAR1MUr5JzmygzdPM3TrtFpGiF9TQMLJMpgXDVMMRpaYA9JK9XLc0s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
