travis:
  secure:
    BINSTAR_TOKEN: msOgydQdJD4a1ru09loW8bn92X2fONdHKOrgxL7J9l9LIFcepCmrRql7I/V3BsYGrxbEIKOGbmNeEzOuvXRvhxec1pR6WZ1HJn9h1HPcu6FaPBZ81r/UDAfmRzENAqUxTClExR62KzHaWRrb+HGGwu0FJqDGrkpv08Jkkawq2R4afPvp5ssimLI2vhqcVvN3sZNdmCZUPkp50880/9DJBHvLlZUhBlduPCsHXKVagnEEmkbIVOhuKVeN3ZJmXLWVRl+24ldnLtDqydE6Ny7n/zZpCDfVHxQeZMDezuHGXTQLfcZyQToYClfdWrNUg9y9zKVTLma/NCl99Blln/gonP8GhJjQnrQNMgZybU6IyuUi6MOw8HSgRLZ4fxJoB9pdkksATfkg6m8irLjJldXnoyyh2SQG+jx94M5yTYjHp2rx/hBfrha00tHc5pQoMzd7rrn36rzEAbIE+ispQR897h/tUhS5e7KDZ+d6b0jtSObSLjA2wThpdLXPje7PYxU98svELjfWjFoKW/TRmKPyLVuxncCgvId9ofwqDyGTjiPdBwW9bnWSzBBpuhBz7zltreX5ulEOJ1FlwdVER9LfjdJXtL4yjYpDZ7G5XdcYTVJDq5RwkkUixYdv6FJ566sovV+u86hNVAxPbe3TeaJ/V0Rm+/eqC8sQMj+/V7h3gdI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
